# This file was generated by GoReleaser. DO NOT EDIT.
cask "costa-beta" do
  name "costa-beta"
  desc ""
  homepage ""
  version "0.1.0-alpha.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "costa"

  on_macos do
    url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_darwin_all.tar.gz"
    sha256 "39f5c5995e2f450d748e8444d6e44e7583d32d5a37b6085b252d24d9038eda8b"
  end

  on_linux do
    on_intel do
      url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_linux_amd64.tar.gz"
      sha256 "111056ffc76c3d909e29bea004212056ccd8f11c67f5cc357a77637053bf0e49"
    end
    on_arm do
      url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_linux_arm64.tar.gz"
      sha256 "0db8b4f16f366350132df43ba7d656744d124ace947581e86bf7adb6c5589a7b"
    end
  end

  # No zap stanza required
end
