# This file was generated by GoReleaser. DO NOT EDIT.
cask "costa-beta" do
  name "costa-beta"
  desc ""
  homepage ""
  version "0.0.1-alpha.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "costa"

  on_macos do
    url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_#{version}_darwin_all.tar.gz"
    sha256 "0c2e472cacaabb8262dd4ac7c0a1b92d329dbe6dce34c907577674fe46809f9b"
  end

  on_linux do
    on_intel do
      url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_#{version}_linux_amd64.tar.gz"
      sha256 "e8793f7db539a647307a1f8fc72c4ca83f5c882a490428e918025119c4820ca0"
    end
    on_arm do
      url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_#{version}_linux_arm64.tar.gz"
      sha256 "ac1eced240192d95adf84ef6eb0d43c22d916cd12c800e9b77010a824ae1c238"
    end
  end

  # No zap stanza required
end
