# This file was generated by GoReleaser. DO NOT EDIT.
cask "costa" do
  name "costa"
  desc ""
  homepage ""
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "costa"

  on_macos do
    url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_#{version}_darwin_all.tar.gz"
    sha256 "270ee3c6a2709d49be647aa76c1ba050c78742489e4aa3e8c537aa0a91da4189"
  end

  on_linux do
    on_intel do
      url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_#{version}_linux_amd64.tar.gz"
      sha256 "31717837660a96f497c5feb87bc4447748c40b2d6908f862e6e9fdf33459f22b"
    end
    on_arm do
      url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_#{version}_linux_arm64.tar.gz"
      sha256 "3e1142f712b86d31439228c98097258fcabeb44ea266090daf0cff270aa2cdee"
    end
  end

  # No zap stanza required
end
