# This file was generated by GoReleaser. DO NOT EDIT.
cask "costa" do
  name "costa"
  desc ""
  homepage ""
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "costa"

  on_macos do
    url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_darwin_all.tar.gz"
    sha256 "7506bc9019073114b0de1e1b11163725acd242ce86047685ffe7271d4f3c2838"
  end

  on_linux do
    on_intel do
      url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_linux_amd64.tar.gz"
      sha256 "b8cc9ba50614c05561bbfc0e21abb4b46caad576b3394ae26ab6506df543932c"
    end
    on_arm do
      url "https://github.com/costa-app/costa-cli/releases/download/v#{version}/costa-cli_linux_arm64.tar.gz"
      sha256 "94132ee452f2149867e755ac32d48fca90c460156f87ee55e5130d1dfc48bbd1"
    end
  end

  # No zap stanza required
end
